### ISSUE TITLE
New version / Jumper T16

### ISSUE THREAD

**Issue by antigravity82** [mikeller/opentx#7]
When will there be a new version? Jumper is now very big on the market. FrSky has now released ACCST 2.0, but the latency is still at 18ms.

Thank you very much!

**Comment by mikeller** [comment]
@antigravity82:

> When will there be a new version?

Never.
OpenTX 2.3 has introduced changes that supersede the improvements made by my patch. If you are still experiencing 18ms latency with OpenTX 2.3 then something in your setup is not working as it should and you'll need to open an issue on https://github.com/opentx/opentx/issues/.
